### ISSUE TITLE
Don't require loading of include.js on every pageview?

### ISSUE THREAD

**Issue by skorokithakis** [mozilla/django-browserid#152]
Is there a way to not require `include.js` to be loaded on every pageview? I was pretty happy with BrowserID when that script only needed to be loaded on my landing page (for logins), but now it needs to load on every single page load, slowing down my page, even though a very very small percentage of pageviews lead to a log out.

It's also causing problems by apparently thinking that my session is expired and forces a logout, only to be led to the front page and automatically log in again. As you can imagine, this is a dealbreaker for users.

Just not loading it doesn't work, because clicking the "logout" button leaves users on the landing page, where BrowserID promptly logs back in again.

Is there a way to prevent loading the script until the user actually clicks the logout button, or similar?

**Comment by skorokithakis** [comment]
I would like to resurrect this. Persona makes *seventeen* requests on page load, even though the vast majority of my users will never log in. This is unacceptable to me, and I would like to dynamically inject include.js (or whatever is making the requests) after the user has clicked the login button. Is there a way to do this?

I don't necessarily need this to be in `django-browserid`, I just need some JS code that will do it. I tried hacking it on my own with the updated version of the library but didn't manage to get it to work.

**Comment by Osmose** [comment]
> I would like to dynamically inject include.js (or whatever is making the requests) after the user has clicked the login button. Is there a way to do this?

I tried making a sample for this and failed as well, because every method of loading the JS in response to a user click I can think of or find functions asynchronously. This breaks because the popup box won't launch outside of a user-initiated event handler, and the async script loading breaks out of that event.

Fixing this requires changes to Persona itself that I doubt will ever happen at this point. :(

Seventeen requests on page load seems excessive, though. What is Persona doing with seventeen requests?

**Comment by skorokithakis** [comment]
It seems to be loading the images for the pop-up. That's odd.

**Comment by Osmose** [comment]
wat

why

why would it do that

**Comment by skorokithakis** [comment]
Maybe I implemented it wrong? See here:

https://www.pastery.net/

I'm just using django-browserid's form, though.

**Comment by Osmose** [comment]
I only see about 5 requests from Persona on page load. Or is this for when you're already logged in?

**Comment by skorokithakis** [comment]
No, this is on a brand-new incognito window:

https://i.imgur.com/ASruDlR.png

It's loading the iframe, so the iframe loads all this. The problem is that the site will have maybe one out of ten thousand page views logging in, so it's very rare that these need to be loaded :/

**Comment by Osmose** [comment]
I still can't replicate your results. I don't get those resources being loaded. I can't think of a reason why you're seeing them and I'm not.

**Comment by skorokithakis** [comment]
Hmm, neither can this:

http://www.webpagetest.org/result/151217_2S_13ZJ/1/details

Must be something in my setup, sorry about that.
